sudo: required
dist: 
   - trusty
   - osx
language: c
cache:
  apt: true
  directories:
    - /home/travis/postgresql
env:
  global:
    - enable_coverage=yes
    - PG_PRELOAD=mysqldb_fdw
  matrix:
    - PGVERSION=9.6
    - PGVERSION=10
    - PGVERSION=11
before_install:
  - git clone -b v0.7.9 --depth 1 https://github.com/citusdata/tools.git
  - sudo make -C tools install
  - setup_apt
  - nuke_pg
install:
  - sudo locale-gen da_DK
  - sudo locale-gen da_DK.utf8
  - sudo pip install cpp-coveralls
  - sudo mysql -u root < sql/mysql.sql
  - install_pg
  - install_custom_pg
before_script:
  - config_and_start_cluster
script: pg_travis_test
after_success:
  - sudo chmod 666 *.gcda
  - coveralls
